es:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - 9200
    - 9300
  volumes_from:
    - data

data:
  image: ubuntu 
  volumes:
    - /data
  command: /bin/bash
